<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyTitle>Scorpio Autofac library</AssemblyTitle>
    <PackageTags>Scorpio;Aspect;Autofac;dependencyinjection;Modularity</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Autofac.Extras.DynamicProxy" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scorpio" />
    <ProjectReference Include="..\Scorpio.Castle.Core\Scorpio.Castle.Core.csproj" />
  </ItemGroup>

</Project>
