<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyTitle>Scorpio AspectCore library</AssemblyTitle>
    <PackageTags>Scorpio;Aspect;AspectCore;dependencyinjection;Modularity</PackageTags>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspectCore.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scorpio" />
  </ItemGroup>

</Project>
